micronaut:
  application:
    name: oauth2MicronautKeycloak
  security:
    authentication: idtoken
    oauth2:
      clients:
        keycloak:
          client-id: ${OAUTH_CLIENT_ID:XXX}
          client-secret: ${OAUTH_CLIENT_SECRET:YYY}
          openid:
            issuer: ${OAUTH_ISSUER}

    endpoints:
      logout:
        enabled: true
        get-allowed: true

netty:
  default:
    allocator:
      max-order: 3
